defmodule YahooFantasyEx.Models.League do
  @moduledoc false
  use YahooFantasyEx.Model,
    fields: [
      allow_add_to_dl_extra_pos: :boolean,
      current_week: :integer,
      draft_status: :atom,
      edit_key: :string,
      end_date: :date,
      end_week: :integer,
      felo_tier: :atom,
      game_code: :atom,
      is_cash_league: :boolean,
      is_pro_league: :boolean,
      league_id: :integer,
      league_key: :string,
      league_type: :atom,
      league_update_timestamp: :integer,
      logo_url: :string,
      name: :string,
      num_teams: :integer,
      renew: &build_renew_key/1,
      renewed: &build_renew_key/1,
      scoring_type: :atom,
      season: :integer,
      short_invitation_url: :string,
      start_date: :date,
      start_week: :integer,
      url: :string,
      weekly_deadline: :atom,
      draft_results: {:many, YahooFantasyEx.Models.League.DraftResult},
      players: {:many, YahooFantasyEx.Models.Player},
      teams: {:many, YahooFantasyEx.Models.Team}
    ]
end
